# Generated by Django 4.1.3 on 2022-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_project', '0002_todolistitem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='user',
            field=models.CharField(default='test_user', max_length=100),
            preserve_default=False,
        ),
    ]
